Name: HMDA Platform CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

env:
  LOCAL_REGISTRY: ghcr.io/${{ github.repository }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    container: sbtscala/scala-sbt:eclipse-temurin-11.0.16_1.7.3_2.12.17
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Build Docker image of HMDA platform
        run: |
          env JAVA_OPTS="-Xss256m -Xmx4096m" sbt -d -v "project hmda-platform" dockerPublishLocalSkipTests
        continue-on-error: false

      - name: Tag and name Docker image
        run: docker tag hmda/hmda-platform:latest ${{ env.LOCAL_REGISTRY }}:${{ github.sha }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: |
          docker push ${{ env.LOCAL_REGISTRY }}:${{ github.sha }}
